# Generated by Django 3.2.7 on 2021-10-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='usuario',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='entrada',
            name='valoracion',
            field=models.IntegerField(default=0),
        ),
    ]
